menu:
  首页: /
  技术: /categories/技术/
  健身: /categories/健身/
  关于: /about/
rss: false
banner: ../images/banner.svg
subtitle: 记录技术学习、工程实践和健身过程
links:

excerpt_link: 继续阅读
fancybox: true

copyright:

sidebar: right
widgets:
  - category

archive_type: yearly
show_count: true
recent_posts_limits: 6

google_analytics:
gauges_analytics:
favicon: /images/favicon.svg
twitter:
fb_admins:
fb_app_id:

disqus_shortname:
